[book]
authors = ["Bit D13"]
language = "en"
multilingual = false
src = "src"
title = "dualSTAKE Documentation: Algorand Liquid Staking with ASA rewards"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/MythFinance/docs.myth.finance"
edit-url-template =  "https://github.com/MythFinance/docs.myth.finance/edit/main/dualSTAKE/{path}"
site-url = "/dualSTAKE/"
mathjax-support = true
